### ISSUE TITLE
Add graceful shutdown to the services

### ISSUE THREAD

**Issue by ludelafo** [csia-pme/csia-pme#13]
# Problem

Whenever a service is stopped, it doesn't announce it to the Engine. The Engine might think the service is still available until the Engine do a health check to take into consideration the service is no longer available.

# Steps to solve the problem

One way would be to listen to the ["shutdown event"](https://fastapi.tiangolo.com/advanced/events/#shutdown-event) from FastAPI in order to notify the Engine that the service is shutting down to allow to remove it.

This will not prevent to notify the Engine if a crash occurs or if the process is forced to shutdown.

**Comment by PxReaz** [comment]
The services now send patch request to the engine to shut themselves when a manual shutdown is launched. If the service is force shut down or if it crashes, then the check routine of the engine will handle the patch of the service to set it as unavailable. If a service is manually registered to an engine, then it also won't patch itself since it as no info about the engine.
